#! /usr/bin/env python

#
# Imports
#
from flask import Flask
from flask import render_template
from flask import json
import sys
import time
import os

#
# initiate the flask application
#
app = Flask(
    __name__,
    static_folder   = '/'.join(os.path.realpath(__file__).split('/')[:-1])+'/static',
    static_url_path = '/static'
    )

@app.route("/")
def start():
    return """
<html>
    <head>
        <title>PHP Test</title>
        <link rel="stylesheet" href="static/css/style.css">
    </head>
    <body>
        <div id="page_row_1">
            <div id="sex">Sex:<br></div><div id="age">Age:<br></div>
        </div>
        <div id="page_row_2">
            <div id="timeatsea">Time at Sea:<br></div><div id="department">Department:<br></div>
        </div>        <br>

        <script src="static/js/d3/d3.js"></script>

        <script src='static/js/oskar.js'></script>
    </body>
</html>"""
#        <script src="http://labratrevenge.com/d3-tip/javascripts/d3.tip.v0.6.3.js"></script>

@app.route("/oskar_data.csv")
def readspercluster():
    test = open('oskar_data.csv').read()

    return test

if __name__ == "__main__":
    app.run(host='0.0.0.0',port=5000,debug=True)